### PR TITLE
Process the catalog queue before looking up in the catalog

### LINKED ISSUE #15: [RFC] Consider processing the catalog queue inside uuidToPhysicalPath
Before #11 the function ``uuidToPhysicalPath`` used to fire a catalog search to return its result.
The catalog search was triggering the catalog queue processor to (re)index the objects in the queue.

That means that right after an object is created or moved, it might happen that it is not yet in the catalog or it is in the catalog with a wrong path.

I discovered this porting some code to Plone 6.

To adjust the code for Plone 6 I had to trigger the call to the ``processQueue`` function myself, e.g.:
```python
from Products.CMFCore.indexing import processQueue
...
        processQueue()
        path = uuidToPhysicalPath(uid)
        # or
        obj = uuidToObject(uuid)
```

Theoretically it is possible to add that call inside the ``uuidToPhysicalPath`` function, but I am not even sure I want to change this behavior myself :)

I just opened this issue to provide a fix (or upgrade path) to other people and to see what other people think about that.

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #15

### CODE REVIEW

**Comment by ale-rt** [comment]
I ran:
```shell
PLONE_APP_UUID_TEST_SPEED_TOTAL=1000 bin/test -s plone.app.uuid
```

to check the speed implications of this patch

## Current master:

```text
Time taken to create 1000 items: 45.802907943725586
Time taken for uuidToPhysicalPath: 0.008858919143676758
Time taken for uuidToURL: 0.3018021583557129
Time taken for uuidToObject: 0.19671344757080078
Time taken for uuidToCatalogBrain: 0.21143126487731934
```

Another run:

```text
Time taken to create 1000 items: 44.901119232177734
Time taken for uuidToPhysicalPath: 0.008687496185302734
Time taken for uuidToURL: 0.3035240173339844
Time taken for uuidToObject: 0.1952672004699707
Time taken for uuidToCatalogBrain: 0.21442627906799316
```


## This branch:

```text
Time taken to create 1000 items: 44.29181718826294
Time taken for uuidToPhysicalPath: 0.019802331924438477
Time taken for uuidToURL: 0.28696346282958984
Time taken for uuidToObject: 0.19346165657043457
Time taken for uuidToCatalogBrain: 0.212846040725708
```

Another run:

```text
Time taken to create 1000 items: 45.579617500305176
Time taken for uuidToPhysicalPath: 0.019948959350585938
Time taken for uuidToURL: 0.29830193519592285
Time taken for uuidToObject: 0.20134234428405762
Time taken for uuidToCatalogBrain: 0.2142777442932129

```

As you can see `uuidToPhysicalPath` takes more than twice the time but it is still pretty fast and there is no impact on `uuidToObject` which is most probably the function you will call in real life.

As mentioned I am not pushing this for this to be merged :)

Do with this PR whatever you like!

**Comment by jensens** [comment]
Huh, I would not merge this in the beta. I am not sure what kind of side effects this might create.

**Review by mauritsvanrees — APPROVED** [review]
I think this PR fine to include. Seems a clear bug fix. Too bad that some of the performance gain is lost, but that can't be helped.

**Comment by jensens** [comment]
I am +/- 0 here, so merge if you think its is fine. If there are any new problems coming up b/c of this we can fix them in a new PR.

**Comment by ale-rt** [comment]
> I am +/- 0 here, so merge if you think its is fine. If there are any new problems coming up b/c of this we can fix them in a new PR.

Actually I came out with #15 and this patch because I noticed that there was an unwanted breaking change when moving to Plone 5 to Plone 6.
Anyway I already solved my problem in another way so I did not actually needed this patch myself and I think for many this will be an edge case.
In the future we can add some warning that this patch will be reverted or whatever.
Anyway I do not think that the call to `processQueue` will cause performance issues to anybody :)

**Pull request merged**
