### PR TITLE
Fix use case where UID to object is failing

### LINKED ISSUE #8: UID to object failing sometimes
We got one use case where `plone.api` could not find one UID, and catalog could:

```python
(Pdb) catalog = api.portal.get_tool('portal_catalog')
(Pdb) catalog.unrestrictedSearchResults(UID=uid)
[<Products.ZCatalog.Catalog.mybrains object at 0x114f3a280>]
(Pdb) catalog.unrestrictedSearchResults(UID=uid)[0]
<Products.ZCatalog.Catalog.mybrains object at 0x114f3a280>
(Pdb) catalog.unrestrictedSearchResults(UID=uid)[0].getObject()
<ATImage at /page/with/image>
(Pdb) api.content.get(UID=uid)
```

Suggest to change [this line](https://github.com/plone/plone.app.uuid/blob/73093c396d7ad80ae46c728eba80caf51675516f/plone/app/uuid/utils.py#L50) to:

```python
catalog.unrestrictedSearchResults(UID=uid)
```

### PR DESCRIPTION
**Pull request by rodfersou**
closes #8

### CODE REVIEW

**Comment by rodfersou** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Seems an obvious fix.
One Jenkins job passes, two have a failure, each a different one. Pretty sure they are unrelated.
I will merge. Thank you!

**Comment by rodfersou** [comment]
@mauritsvanrees I'm thinking now about this problem, you think this might happen because the object or one of its parent's folders are not published?

**Comment by mauritsvanrees** [comment]
Yes, that could be an explanation. @fredvd was standing next to me and we saw something similar a while ago, though not sure if that was using this part of the code. A carousel with sliders was working fine for admins but not for editors: if one of the items had a publication date in the future, the whole carousel would fail, and they could not edit it to fix it.

**Comment by fredvd** [comment]
>  if one of the items had a publication date in the future, the whole carousel would fail, and they could not edit it to fix it.

More context: This was a few years ago in the carousel tile from collective.cover: if the expiry_date had already passed, the catalog query in the uuid-to-object function would filter out the expired items for logged in users without Manager permission, breaking  the edit form. I tried to look for it, but I cannot find back the patch in the customer project. 

Ah I found it. I fixed a similar function in collective.cover at that time, see the comment:

https://github.com/collective/collective.cover/blob/1162d6d77a79ef5b2e667539a589e970566a1941/src/collective/cover/utils.py#L24-L33

**Comment by rodfersou** [comment]
I wonder is if this change is still valid or should be reverted and the original code was right

**Comment by rodfersou** [comment]
I can revisit the problem running with manager super powers and see if problem happen

**Comment by rodfersou** [comment]
Just confirmed that the problem persist if run as manager:

```python
        with api.env.adopt_roles(['Manager']):
            obj = api.content.get(UID=uid)
```

```python
(Pdb) obj is None
True
```

So looks like it is really a bug.

```python
(Pdb) catalog.searchResults(UID=uid)
[]
(Pdb) catalog(UID=uid)
[]
(Pdb) catalog.unrestrictedSearchResults(UID=uid)
[<Products.ZCatalog.Catalog.mybrains object at 0x1144868a0>]
```

But maybe we need to make it use the `unrestrictedSearchResults` just when run with
 super powers ( `api.env.adopt_roles(['Manager'])` )

**Comment by rodfersou** [comment]
@mauritsvanrees @fredvd can you please guide me on how to prepare the code for this?

**Pull request merged**
